### ISSUE TITLE
Support CRD

### ISSUE THREAD

**Issue by cpoulsen** [toboshii/hajimari#37] opened 2022-03-04 21:41 UTC
**Is your feature request related to a problem? Please describe.**
Seems like it only works for type: Ingress. It would be nice to add support for Traefiks IngressRoute for instance.

**Describe the solution you'd like**
Some way of configuring CRD ingress

**Describe alternatives you've considered**
Hardcoding the ingresses to the applications list, which seems rather pointless.

**Comment by toboshii** [comment] 2022-08-30 07:58
Duplicate of #33

**Closed by toboshii** 2022-08-30 07:58 UTC
Labels: duplicate
